---
- name: add PPA repos
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items:
    - ppa:webupd8team/atom
    - ppa:webupd8team/sublime-text-3
  sudo: yes

- name: Update caches after PPA being added
  apt: update_cache=yes
  sudo: yes

- name : install IDEs from PPAs
  apt: name="{{ item }}" state=present
  with_items:
    - atom
    - sublime-text-installer
  sudo: yes
